service:
  name: adventar-frontend

package:
  exclude:
    - .nuxt/**
    - dist/**

plugins:
  - serverless-offline

provider:
  name: aws
  stage: prod
  runtime: nodejs10.x
  region: ap-northeast-1
  deploymentBucket:
    name: adventar
  deploymentPrefix: serverless-deploy
  apiGateway:
    logs: true
  environment:
    API_BASE_URL: https://api.adventar.org
    NODE_ENV: production
    TZ: Asia/Tokyo

functions:
  main:
    handler: server.handler
    events:
      - http:
          method: get
          path: calendars/{id}
      - http:
          method: get
          path: users/{id}
