service: adventar-batch

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: go1.x
  memorySize: 256
  timeout: 300
  region: ap-northeast-1
  deploymentBucket:
    name: adventar
  vpc:
    subnetIds:
      - subnet-059a83efe99ee37ee # public_1a
    securityGroupIds:
      - sg-073b60f32ebeb3cef # default
  deploymentPrefix: serverless-deploy
  environment: ${file(./env.${self:provider.stage}.yml)}

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  updateEntrySiteInfo:
    handler: bin/update_entry_site_info
    events:
      - schedule: cron(0 15-23 30 11 ? *)
      - schedule: cron(0 * 1-25 12 ? *)
