service: adventar-batch

provider:
  name: aws
  stage: prod
  runtime: go1.x
  memorySize: 256
  region: ap-northeast-1
  deploymentBucket:
    name: adventar
  vpc:
    subnetIds:
      - subnet-059a83efe99ee37ee # public_1a
    securityGroupIds:
      - sg-073b60f32ebeb3cef # default
  deploymentPrefix: serverless-deploy
  environment:
    TZ: Asia/Tokyo
    DATABASE_SOURCE: ${env:DATABASE_SOURCE, 'root@tcp(host.docker.internal:13306)/adventar_dev'}
    CURRENT_DATE: ${env:CURRENT_DATE, ''}

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  update_entry_site_info:
    handler: bin/update_entry_site_info
    events:
      - schedule: cron(0 15-23 30 11 ? *)
      - schedule: cron(0 * 1-25 12 ? *)
