service: adventar-image-server

plugins:
 - serverless-apigw-binary

provider:
  name: aws
  stage: prod
  runtime: go1.x
  region: ap-northeast-1
  deploymentBucket:
    name: adventar
  deploymentPrefix: serverless-deploy
  environment:
    DIGEST_SALT: ${env:DIGEST_SALT}

custom:
  apigwBinary:
    types:
      - '*/*'

package:
  exclude:
    - ./**
  include:
    - ./image-server

functions:
  main:
    handler: image-server
    events:
      - http:
          method: GET
          path: img/{digest}
