version: '3'
services:
  app:
    image: hokaccha/adventar-app:beta-1
    logging:
      driver: awslogs
      options:
        awslogs-group: ecs-hello
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: ecs
  envoy:
    image: hokaccha/adventar-envoy:beta-2
    ports:
      - "80:80"
    command: /usr/local/bin/envoy -c /etc/envoy/envoy-prod.yaml
    logging:
      driver: awslogs
      options:
        awslogs-group: ecs-hello
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: ecs
